import java.io.IOException;
import java.util.LinkedList;

public class Basic {
    public static void main(String[] args) {
        try {
            String filePath = "test.basic"; // this is the path to your BASIC file
            // Initialize the Lexer with the file path
            Lexer lexer = new Lexer();
            LinkedList<Token> tokens = lexer.lex(filePath);

            // Initialize the Parser with the tokens generated by the lexer
            Parser parser = new Parser(tokens);
            Node ast = parser.parse(); // Parse the tokens to generate the AST

            // Output the AST
            System.out.println("After Parsing");
            System.out.println(ast.toString());
        } catch (IOException | LexerException e) {
            System.err.println("An error occurred:");
            e.printStackTrace();
        }
    }
}
